config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources  :courses
  root 'courses#index'

resources :subscriptions

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  owner_id    :integer
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Course < ActiveRecord::Base
	has_and_belongs_to_many :users
	belongs_to :owner, class_name: :User
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#
class User < ActiveRecord::Base
  has_and_belongs_to_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def is_enroled?(course)
  	self.courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user!

	def index
    @courses = Course.all
  end

	def show
    @course = Course.find(params[:id])
  	end


	def new

	end

	def create
		@course = Course.new(course_params)
		@course.owner = current_user
   		@course.save
  		redirect_to @course
	end
 

private
  def course_params
    params.require(:course).permit(:name, :description, :owner_id)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

def index
	
end

def new
end

def show
	@course = Course.find(params[:id])
end

def create
 	@course = Course.find(params[:course_id])
 	@course.users << current_user
 	@course.save  
 	redirect_to @course
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/courses/index.html.erb
<h1>Todos los cursos</h1>
 
<table>
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
  </tr>
 
  <% @courses.each do |course| %>
  
    <tr>
      <td><%= course.name %></td>
      <td><%= course.description %></td>
      <td><%= link_to 'Ir al Curso', course_path(course)%></td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Crear Nuevo Curso', new_course_path %>
</p>

app/views/courses/new.html.erb
<h1>Nuevo Curso</h1>

<%= form_for :course, url: courses_path do |f| %>
  <p>
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :Descripción %><br>
    <%= f.text_area :description %>
  </p>
  		
  	<p>
    	<%= f.submit :Guardar %>
  	</p>
<% end %>

app/views/courses/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @course.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @course.description %>
</p>


<% if current_user != @course.owner  && !current_user.is_enroled?(@course) %>
	<%= form_for :susbcription, url: subscriptions_path do |f| %>
	<%= hidden_field_tag 'course_id', @course.id %>
   	<%= f.submit :Inscribirse %>

 <% end %> 

<% end %>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Udemi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>